#!/usr/bin/env bash

# update the advanced package tool (apt)
apt-get update
apt-get upgrade

# install git
apt install git

# git config --global user.email "you@example.com"
git config --global user.email "afrancocedeno@gmail.com"

# git config --global user.name "Your Name"
git config --global user.name "Alejandro Franco Cedeño"

# 
echo "PS1=\"\W > \"" >> ~/.bashrc

# g command to add, commit and push and chmod .py and .rb files
echo "
#!/bin/bash
if [[ \$1 == *.py ]] || [[ \$1 == *.rb ]]; then
    chmod +x \$1
    if [[ \$1 == *.py ]]; then
        c=\$(pep8 \$1 | wc -l)
        if [ \$c -ge \"1\" ]; then
            pep8 \$1
            exit
        fi
    fi
fi
git add \$1
git commit -m \"\$2\"
git push
" >> /usr/bin/g

# set executable the g command
chmod +x /usr/bin/g

# usage: g FILE_NAME "COMMIT DESCRIPTION"
